[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$major.$minor.$patch$prerelease"
version_scheme = "semver"
version = "1.8.1"
update_changelog_on_bump = true
version_files = [
    "pygeoapi-eoxhub/Chart.yaml"
]
