apiVersion: v1
kind: Service
metadata:
  name: {{ include "base.fullname" . }}
  labels:
{{ include "base.labels" . | indent 4 }}
{{ if .Values.enableEoxhubAppAnnotations }}
  # NOTE: more recent eoxhubs need the annoations only in the servce, here it's still duplicated for compatibility
  annotations:
    eoxhub/app-name: "Headless"
    eoxhub/app-logo: "https://pygeoapi.io/img/pygeoapi-logo.png"
    eoxhub/stop-if-unused: "false"
{{ end }}

spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "base.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
