existingNfs:
  enabled: true
  nfsServer: "fs-67cadc3e.efs.eu-central-1.amazonaws.com"
  nfsShare: "edc-jupyter-user-pvc-3157bd51-f57d-11e9-adac-062139e27092"


    
extraVolumes: []
  # - name: shared
  #   persistentVolumeClaim:
  #     claimName: jupyterhub-core-shared
extraVolumeMounts: []
  # - mountPath: /home/jovyan/extra
  #   name: shared
  #   subPath: "eurodatacube0"


# DEPRECATED: this syntax only allows 1 mount per volume
extraPvcs: []
  #- claim_name: ama-jupyter-eox
  #  mount_path: /home/jovyan/eox
  #  sub_path: my-dir  # optional


defaultImage: "527538141574.dkr.ecr.eu-central-1.amazonaws.com/eurodatacube-jupyter-user:0.24.5"
allowedImagesRegex: ""
imagePullSecret: ""
logOutput: false

s3:
  enabled: false
  bucketName: ""
  secretName: "edc-bucket"
  mountPath: ""  # only image mode
  s3Url: "https://s3-eu-central-1.amazonaws.com"
  # NOTE; this is applied to the job as well as the server
  resourceLimits: {}
  resourceRequests: {}

jupyterBaseUrl: "https://edc-jupyter.hub.eox.at"

ingressEnabled: true
# ingressUrl: "foo.example.com"

outputDirectory: "/home/jovyan/job-output"
resultsInOutputDir: false
condaStoreGroups: []  # ["eurodatacube25", "mygroup"]

pygeoapi:
  # This block concerns the pygeoapi server deployment itself
  # Other options are intended to affect the job pods
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hub.jupyter.org/node-purpose
            operator: In
            values:
            - user
  tolerations: []
  # tolerations: [{"key": "hub.eox.at/processing", "operator": "Exists", "effect": "NoSchedule"}]
  logLevel: INFO  # "DEBUG" for more verbosity

secrets: []
autoMountSecrets: False

checkoutGitRepo:
  enabled: false
  url: ""
  secretName: "pygeoapi-git"

# NOTE: this is about the job pod, not the pygeoapi server job
nodePurposeLabelKey: "hub.eox.at/node-purpose"
defaultNodePurpose: "c1"
allowedNodePurposesRegex: ""
tolerations: []
# tolerations: [{"key": "hub.eox.at/processing", "operator": "Exists", "effect": "NoSchedule"}]

results:
  resultsLinkTemplate: ""  # link with job_id as template parameter as in "example.com/{job_id}"

job:
  mode: "notebook"  # or 'argo' or 'image'

  logQueryEndpoint: ""

  # TODO: move other global values to job (breaking change)
  runAsUser: null
  runAsGroup: null

  extraResourceLimits: {}
  extraResourceRequests: {}

  command: ""  # only image mode
  parametersEnv: {}  # only image mode

fargate:
  allow: false

# NOTE: if the fullname is overridden to be pygeoapi, we don't need this svc
enableEoxhubGatewayService: false
enableEoxhubAppAnnotations: false
# for newer eoxhub-gateway 
eoxhhubServiceAnnotations:
  eoxhub/app-logo: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><title>application-cog</title><path
      d="M21.7 18.6V17.6L22.8 16.8C22.9 16.7 23 16.6 22.9 16.5L21.9 14.8C21.9 14.7
      21.7 14.7 21.6 14.7L20.4 15.2C20.1 15 19.8 14.8 19.5 14.7L19.3 13.4C19.3 13.3
      19.2 13.2 19.1 13.2H17.1C16.9 13.2 16.8 13.3 16.8 13.4L16.6 14.7C16.3 14.9 16.1
      15 15.8 15.2L14.6 14.7C14.5 14.7 14.4 14.7 14.3 14.8L13.3 16.5C13.3 16.6 13.3
      16.7 13.4 16.8L14.5 17.6V18.6L13.4 19.4C13.3 19.5 13.2 19.6 13.3 19.7L14.3 21.4C14.4
      21.5 14.5 21.5 14.6 21.5L15.8 21C16 21.2 16.3 21.4 16.6 21.5L16.8 22.8C16.9
      22.9 17 23 17.1 23H19.1C19.2 23 19.3 22.9 19.3 22.8L19.5 21.5C19.8 21.3 20 21.2
      20.3 21L21.5 21.4C21.6 21.4 21.7 21.4 21.8 21.3L22.8 19.6C22.9 19.5 22.9 19.4
      22.8 19.4L21.7 18.6M18 19.5C17.2 19.5 16.5 18.8 16.5 18S17.2 16.5 18 16.5 19.5
      17.2 19.5 18 18.8 19.5 18 19.5M11 18C11 14.1 14.1 11 18 11C20 11 21.7 11.8 23
      13.1V4C23 2.9 22.1 2 21 2H3C1.9 2 1 2.9 1 4V20C1 21.1 1.9 22 3 22H12.3C11.5
      20.9 11 19.5 11 18M3 4H21V7H3V4Z" /></svg>'
  eoxhub/app-name: Headless
  eoxhub/stop-if-unused: "false"
genericProcesses: []

argoWorkflows: []  # 
